- name: create app directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: Creating roboshop system user
  ansible.builtin.user:
    name: roboshop
    shell: /sbin/nologin
    system: true
    home: /app

- name: download catalogue code
  ansible.builtin.get_url:
    url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip
    dest: /tmp/catalogue.zip

# This module by default thinks file exist on ansible control server, needs to extract on to remote machine. Here remote machine is catalogue
#  remote_src: yes means files already exist in catalogue server
- name: extract catalogue code
  ansible.builtin.unarchive:
    src: /tmp/catalogue.zip
    dest: /app
    remote_src: yes