- name: create app directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: Creating roboshop system user
  ansible.builtin.user:
    name: roboshop
    shell: /sbin/nologin
    system: true
    home: /app

- name: "download {{ component}} code"
  ansible.builtin.get_url:
    url: "https://roboshop-artifacts.s3.amazonaws.com/{{ component }}-v3.zip"
    dest: "/tmp/{{ component }}.zip"

# This module by default thinks file exist on ansible control server, needs to extract on to remote machine. Here remote machine is component
#  remote_src: yes means files already exist in component server
- name: "extract {{ component }} code"
  ansible.builtin.unarchive:
    src: "/tmp/{{ component }}.zip"
    dest: /app
    remote_src: yes